workflows:
  default-workflow:
    name: Chat App APK Builder
    instance_type: mac_mini_m1
    max_build_duration: 15
    environment:
      flutter: stable
    scripts:
      - name: Fetch Flutter dependencies
        script: flutter pub get
      - name: Build Android APK
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    publishing:
      email:
        recipients:
          - naveengowda607@gmail.com
